package by.epam.bakery.controller.command;

public enum CommandName {
    SHOW_MAIN_PAGE,
    WRONG_COMMAND,
    LOGIN,
    LOG_OUT,
    SORT_BY_INCREASE_PRICE,
    SORT_BY_REDUCTION_PRICE,
    PERSONAL_ACCOUNT,
    CHANGE_NAME,
    CHANGE_SURNAME,
    CHANGE_ADDRESS,
    CHANGE_PATRONYMIC,
    CHANGE_PHONE,
    SHOW_FEEDBACK,
    ADD_FEEDBACK,
    SHOW_ABOUT_US,
    SHOW_CONTACTS,
    SHOW_DELIVERY,
    ADD_PIE,
    CLEAR_BASKET,
    ADD_ORDER
}
